### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "shinjw0926@naver.com",
  "password": "1234"
}

### 인증 페이지 요청
GET http://localhost:8080/test
Cookie: SESSION=4ba17f0c-9bdd-4194-a6dd-0d79fd875487
